title:              Daily_Update
email:              wklyu@umich.edu
description:        A Weikun Lyu's Daily post for my CS career
author:             Weikun Lyu
baseurl:            "/daily_update"
url:                "https://wklyu.github.io"

# Social Profiles
twitter_username:   David_LWK
github_username:    wklyu
linkedin_username:  WeikunLyu

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
